export enum CatppuccinBackgroundColour {
    ROSEWATER = "dark:bg-ctp-rosewater bg-ctp-l-rosewater",
    FLAMINGO = "dark:bg-ctp-flamingo bg-ctp-l-flamingo",
    PINK = "dark:bg-ctp-pink bg-ctp-l-pink",
    MAUVE = "dark:bg-ctp-mauve bg-ctp-l-mauve",
    RED = "dark:bg-ctp-red bg-ctp-l-red",
    MAROON = "dark:bg-ctp-maroon bg-ctp-l-maroon",
    PEACH = "dark:bg-ctp-peach bg-ctp-l-peach",
    YELLOW = "dark:bg-ctp-yellow bg-ctp-l-yellow",
    GREEN = "dark:bg-ctp-green bg-ctp-l-green",
    TEAL = "dark:bg-ctp-teal bg-ctp-l-teal",
    SKY = "dark:bg-ctp-sky bg-ctp-l-sky",
    SAPPHIRE = "dark:bg-ctp-sapphire bg-ctp-l-sapphire",
    BLUE = "dark:bg-ctp-blue bg-ctp-l-blue",
    LAVENDER = "dark:bg-ctp-lavender bg-ctp-l-lavender",
    TEXT = "dark:bg-ctp-text bg-ctp-l-text",
}

export enum CatppuccinTextColour {
    ROSEWATER = "dark:text-ctp-rosewater text-ctp-l-rosewater",
    FLAMINGO = "dark:text-ctp-flamingo text-ctp-l-flamingo",
    PINK = "dark:text-ctp-pink text-ctp-l-pink",
    MAUVE = "dark:text-ctp-mauve text-ctp-l-mauve",
    RED = "dark:text-ctp-red text-ctp-l-red",
    MAROON = "dark:text-ctp-maroon text-ctp-l-maroon",
    PEACH = "dark:text-ctp-peach text-ctp-l-peach",
    YELLOW = "dark:text-ctp-yellow text-ctp-l-yellow",
    GREEN = "dark:text-ctp-green text-ctp-l-green",
    TEAL = "dark:text-ctp-teal text-ctp-l-teal",
    SKY = "dark:text-ctp-sky text-ctp-l-sky",
    SAPPHIRE = "dark:text-ctp-sapphire text-ctp-l-sapphire",
    BLUE = "dark:text-ctp-blue text-ctp-l-blue",
    LAVENDER = "dark:text-ctp-lavender text-ctp-l-lavender",
    TEXT = "dark:text-ctp-text text-ctp-l-text",
}

export enum CatppuccinFillColour {
    ROSEWATER = "dark:fill-ctp-rosewater fill-ctp-l-rosewater",
    FLAMINGO = "dark:fill-ctp-flamingo fill-ctp-l-flamingo",
    PINK = "dark:fill-ctp-pink fill-ctp-l-pink",
    MAUVE = "dark:fill-ctp-mauve fill-ctp-l-mauve",
    RED = "dark:fill-ctp-red fill-ctp-l-red",
    MAROON = "dark:fill-ctp-maroon fill-ctp-l-maroon",
    PEACH = "dark:fill-ctp-peach fill-ctp-l-peach",
    YELLOW = "dark:fill-ctp-yellow fill-ctp-l-yellow",
    GREEN = "dark:fill-ctp-green fill-ctp-l-green",
    TEAL = "dark:fill-ctp-teal fill-ctp-l-teal",
    SKY = "dark:fill-ctp-sky fill-ctp-l-sky",
    SAPPHIRE = "dark:fill-ctp-sapphire fill-ctp-l-sapphire",
    BLUE = "dark:fill-ctp-blue fill-ctp-l-blue",
    LAVENDER = "dark:fill-ctp-lavender fill-ctp-l-lavender",
    TEXT = "dark:fill-ctp-text fill-ctp-l-text",
}

export enum CatppuccinStrokeColour {
    ROSEWATER = "dark:stroke-ctp-rosewater stroke-ctp-l-rosewater",
    FLAMINGO = "dark:stroke-ctp-flamingo stroke-ctp-l-flamingo",
    PINK = "dark:stroke-ctp-pink stroke-ctp-l-pink",
    MAUVE = "dark:stroke-ctp-mauve stroke-ctp-l-mauve",
    RED = "dark:stroke-ctp-red stroke-ctp-l-red",
    MAROON = "dark:stroke-ctp-maroon stroke-ctp-l-maroon",
    PEACH = "dark:stroke-ctp-peach stroke-ctp-l-peach",
    YELLOW = "dark:stroke-ctp-yellow stroke-ctp-l-yellow",
    GREEN = "dark:stroke-ctp-green stroke-ctp-l-green",
    TEAL = "dark:stroke-ctp-teal stroke-ctp-l-teal",
    SKY = "dark:stroke-ctp-sky stroke-ctp-l-sky",
    SAPPHIRE = "dark:stroke-ctp-sapphire stroke-ctp-l-sapphire",
    BLUE = "dark:stroke-ctp-blue stroke-ctp-l-blue",
    LAVENDER = "dark:stroke-ctp-lavender stroke-ctp-l-lavender",
    TEXT = "dark:stroke-ctp-text stroke-ctp-l-text",
}

export enum CatppuccinOutlineColour {
    ROSEWATER = "dark:outline-ctp-rosewater outline-ctp-l-rosewater",
    FLAMINGO = "dark:outline-ctp-flamingo outline-ctp-l-flamingo",
    PINK = "dark:outline-ctp-pink outline-ctp-l-pink",
    MAUVE = "dark:outline-ctp-mauve outline-ctp-l-mauve",
    RED = "dark:outline-ctp-red outline-ctp-l-red",
    MAROON = "dark:outline-ctp-maroon outline-ctp-l-maroon",
    PEACH = "dark:outline-ctp-peach outline-ctp-l-peach",
    YELLOW = "dark:outline-ctp-yellow outline-ctp-l-yellow",
    GREEN = "dark:outline-ctp-green outline-ctp-l-green",
    TEAL = "dark:outline-ctp-teal outline-ctp-l-teal",
    SKY = "dark:outline-ctp-sky outline-ctp-l-sky",
    SAPPHIRE = "dark:outline-ctp-sapphire outline-ctp-l-sapphire",
    BLUE = "dark:outline-ctp-blue outline-ctp-l-blue",
    LAVENDER = "dark:outline-ctp-lavender outline-ctp-l-lavender",
    TEXT = "dark:outline-ctp-text outline-ctp-l-text",
}
